### PR TITLE
fix scroll bar

### LINKED ISSUE #671: Scroll issue
Hey, I encountered an issue, when having scroll view, I am unable to scroll with mouse and handle. Only scroll wheel works.

It doesn't work as well in the 'toto-complex' example.

I am using Windows 11 with newest floem master on vello.

### PR DESCRIPTION
**Pull request by jrmoulton**
fixes #671 

Fixes the bounds check and in doing so now makes the assumption that the scroll bars should always be in view regardless of the distance scrolled. ie if there is horizontal scrolling the vertical bar should remain fixed in place. 

this is the behavior I would expect so I'm not sure why it wasn't like that before

### CODE REVIEW

File: src/views/scroll.rs [hunk 1]
```diff
@@ -513,10 +513,10 @@ impl Scroll {
         let top_y_offset = ((self.total_rect.height() - length) * percent_scrolled).ceil();
         let bottom_y_offset = top_y_offset + length;
 
-        let x0 = scroll_offset.x + self.total_rect.width() - bar_width - bar_pad;
```
Comment (jrmoulton) [inline src/views/scroll.rs:516]: I don't know why this was here before

**Comment by jrmoulton** [comment]
Ok never mind. this has issues
